name: openproject

services:

  app:
    image: openproject/openproject:${OPENPROJECT_V}
    restart: always
    volumes:
      - openproject_pgdata:/var/openproject/pgdata
      - openproject_assets:/var/openproject/assets 
    environment:
      - TZ=${DEFAULT_TIME_ZONE}
      - SECRET_KEY_BASE=${OPENPROJECT_SECRET_KEY_BASE}
      - OPENPROJECT_HOST__NAME=${OPENPROJECT_HOST_NAME}:${WEB_HTTP_PORT}
      - OPENPROJECT_HTTPS=${OPENPROJECT_HTTPS}
      - OPENPROJECT_DEFAULT__LANGUAGE=de
    ports:
      - ${WEB_HTTP_PORT}:80


volumes:
  openproject_pgdata:
  openproject_assets: